import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Container } from '@mui/material';

import Header from '@/components/Layouts/Header';
import Footer from '@/components/Layouts/Footer';
import Sidebar from '@/components/Layouts/Sidebar/Sidebar';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header />
                <Container maxWidth="lg">
                    <div className="flex">
                        <main style={{ flex: 1 }}>{children}</main>
                        <Sidebar />
                    </div>
                </Container>
                <Footer />
            </body>
        </html>
    );
}
